name: build CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - closed
    branches:
      - master
      - main

jobs:
  build:
    name: 构建任务
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      packages: write
      contents: read
    steps:
      - name: 拉取仓库代码
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 构建 Docker 镜像
        id: build
        run: docker compose build

      - name: 登录 GitHub Packages Docker 镜像仓库
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送 Docker 镜像
        run: docker push ghcr.io/goudanwoo/electrumx-proxy
